# Generated by Django 2.2.8 on 2020-03-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_course', models.CharField(max_length=10, verbose_name='Código')),
                ('name_course', models.CharField(max_length=100, verbose_name='Curso')),
                ('website_course', models.URLField(blank=True, help_text='Escriba la dirección completa incluido http:// o https://', max_length=250, null=True, verbose_name='Web Site')),
                ('description_course', models.TextField(blank=True, max_length=30, null=True, verbose_name='Descripción')),
                ('prerequisites_course', models.TextField(blank=True, max_length=30, null=True, verbose_name='Pre-requisitos')),
                ('course_document', models.FileField(blank=True, help_text='Documento describiendo el contenido del curso/publicidad.', null=True, upload_to='cursos/', verbose_name='Documento del curso')),
                ('past_course', models.BooleanField(default=False, verbose_name='Descontinuado')),
            ],
            options={
                'verbose_name_plural': 'Cursos del Instituto',
                'ordering': ['id'],
            },
        ),
    ]
