# Generated by Django 2.2.8 on 2020-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='media/img.png', help_text='Imagen de portada', null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_course',
            field=models.TextField(blank=True, help_text='Maximo 100 caracteres', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites_course',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Pre-requisitos'),
        ),
    ]
