# Generated by Django 2.2.8 on 2020-03-29 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200324_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lectura'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen de portada', null=True, upload_to='cursosImg/'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
