# Generated by Django 2.2.8 on 2020-03-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200329_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Docente'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Titulo',
            field=models.CharField(max_length=50),
        ),
    ]
